# Generated by Django 3.1.7 on 2021-03-27 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('abstract', models.TextField(max_length=2000, verbose_name='概要')),
                ('short_name', models.CharField(default='null', max_length=20, unique=True, verbose_name='省略形')),
                ('start_date', models.DateTimeField(verbose_name='開始日時')),
                ('end_date', models.DateTimeField(verbose_name='終了日時')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('question', models.TextField(max_length=2000, verbose_name='問題')),
                ('answer', models.TextField(max_length=2000, verbose_name='正解')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='回答')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.problem', verbose_name='問題')),
            ],
        ),
    ]
