# Generated by Django 3.1.7 on 2021-03-31 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0003_submission_submission_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty', models.IntegerField(default=0, verbose_name='ペナルティ')),
                ('score', models.IntegerField(default=0, verbose_name='得点')),
                ('first_accept_date', models.TimeField(verbose_name='時間')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.problem', verbose_name='問題')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='参加者')),
            ],
        ),
    ]
