# Generated by Django 3.1.7 on 2021-03-31 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='結果'),
        ),
    ]
