# Generated by Django 3.1.7 on 2021-03-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_submission_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='penalty',
            field=models.IntegerField(default=5, verbose_name='ペナルティ(分)'),
        ),
    ]
