# Generated by Django 3.1.7 on 2021-03-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_contest_penalty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='first_accept_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='時間'),
        ),
    ]
