# Generated by Django 3.1.7 on 2021-03-31 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0011_contestscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestscore',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='時間'),
        ),
    ]
