# Generated by Django 3.1.7 on 2021-03-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0012_auto_20210331_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='order',
            field=models.CharField(default='A', max_length=5, verbose_name='問題番号(アルファベット)'),
        ),
    ]
