# Generated by Django 3.1.7 on 2021-03-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0014_contestscore_penalty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemscore',
            name='accepted_date',
        ),
        migrations.AddField(
            model_name='problemscore',
            name='time_sec',
            field=models.IntegerField(default=0, verbose_name='時間(s)'),
        ),
        migrations.AlterField(
            model_name='contestscore',
            name='time',
            field=models.IntegerField(default=0, verbose_name='時間(s)'),
        ),
    ]
