# Generated by Django 3.1.7 on 2021-04-08 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0016_auto_20210331_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='タイトル')),
                ('note', models.TextField(max_length=200, verbose_name='備考')),
                ('test_input', models.TextField(max_length=2000, verbose_name='入力')),
                ('test_output', models.TextField(max_length=2000, verbose_name='出力')),
                ('is_sample', models.BooleanField(default=False, verbose_name='サンプル')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.problem', verbose_name='問題')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10, verbose_name='状態')),
                ('output', models.TextField(max_length=2000, verbose_name='出力結果')),
                ('error', models.TextField(max_length=2000, verbose_name='エラー出力')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.submission', verbose_name='提出')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.testcase', verbose_name='テストケース')),
            ],
        ),
    ]
