# Generated by Django 3.1.7 on 2021-04-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0018_auto_20210408_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='waiting_judge',
        ),
        migrations.AddField(
            model_name='submission',
            name='judged_test_case',
            field=models.IntegerField(default=0, verbose_name='ジャッジ済テストケースの数'),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(default='WAIT', max_length=10, verbose_name='状態'),
        ),
        migrations.AddField(
            model_name='submission',
            name='total_test_case',
            field=models.IntegerField(default=0, verbose_name='テストケースの数'),
        ),
    ]
