# Generated by Django 3.1.7 on 2021-04-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0023_auto_20210411_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='order',
            field=models.CharField(default='A', max_length=5, verbose_name='問題番号(アルファベット)'),
        ),
    ]
