# Generated by Django 3.1.7 on 2021-04-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0024_auto_20210411_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='released',
            field=models.BooleanField(default=False, verbose_name='公開済'),
        ),
    ]
